### ISSUE TITLE
Add support for dispatching input on specific window

### ISSUE THREAD

**Issue by philipfeldmann** [Robot/robot#104]
Would it be possible to allow input such as a key or mousepress on a specific window, without it being active? All inputs are currently global. I'm not entirely sure if this is possible cross platform, but windows itself should allow this.

PS: loving the node version of robot so far, it's great!

**Comment by dkrutsko** [comment]
Hey there, this is actually addressed by [this issue](https://github.com/Robot/robot/issues/16). The main problem is that it doesn't work for all applications. For example, if the application is getting input directly from the keyboard, such as GTA V, then using [PostMessage](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644944(v=vs.85).aspx) won't work. Another example is applications checking if the main window is active before accepting input, such as Overwatch. So unless there's some other method, like perhaps through a driver or code injection, there's no real way to do it on Windows in all instances, let alone other platforms. But I'll keep looking and perhaps implement the PostMessage method for applications that do support it.

**Comment by philipfeldmann** [comment]
That's unfortuante, PostMessage is what I wanted to reference. Do you have any information about mouse input?

**Comment by dkrutsko** [comment]
Given that most applications use [GetCursorPos](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648390(v=vs.85).aspx) and [SetWindowsHookEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644990(v=vs.85).aspx), I'm not sure it could be easily doable without some sort of code injection.
