### ISSUE TITLE
keyboard.sendMessage in background to windowhandle

### ISSUE THREAD

**Issue by fortiZde** [Robot/robot#109]
Hey, guys.
I love this library. I'm currently developing a bot for a game that should also work in the background. Most of my bots I developed with C#. There I was also able to send keystrokes for games in the background. 

I also want this functionality for robot-js. 
REF: [MSDN::SendMessage function](https://msdn.microsoft.com/de-de/library/windows/desktop/ms644950(v=vs.85).aspx)

Best regards

**Comment by dkrutsko** [comment]
Hello, thank you for your feedback. This feature has actually been requested in https://github.com/Robot/robot/issues/16, I wish I had an ETA for you. One of the issues is that there is no consistent way of sending inputs to specific windows. Sometimes `SendMessage` works, as you mentioned and sometimes not. I'm also not aware of any method of injecting input to windows that rely on raw input or check that they're active before accepting input. These techniques are used as counter measures against automated gameplay and can't be bypassed without detouring or patching of some kind. Moreover, I'm not sure if there are similar restrictions on Mac & Linux. Regardless, I might just end up exposing [`PostMessage`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644944(v=vs.85).aspx). In the meantime, you should be able to use that native function directly using existing robot key constants.

**Comment by fortiZde** [comment]
Sorry didn't found that #16 in with my keywords while searching. Thx so far.
