### ISSUE TITLE
Please make a python binding of this library!

### ISSUE THREAD

**Issue by Jah-On** [Robot/robot#117]
Hi!
This lib looks really cool! I would find it super useful if you made a python version!
Thanks!

**Comment by dkrutsko** [comment]
Hey there, yes both a Python and Golang version of this library is something which I have thought of writing. Though I'm a bit unfamiliar with both. If I can stay interested in this project long enough, I'm sure this is something that I will implement.

Although actually, it looks like [someone](https://github.com/go-vgo/robotgo) does have a library similar to Robot written in Golang. And [another one](https://github.com/vcaesar/robotn) which may have similar functionality you're looking for in Python.

**Comment by Jah-On** [comment]
Thank you for the reply! I actually do not need this anymore but I'm sure others would benefit from it.
