### ISSUE TITLE
Improve test case flexibility

### ISSUE THREAD

**Issue by dkrutsko** [Robot/robot#27]
Right now it's a huge pain to test the library. There's no way of skipping specific tests and some of those tests take up a lot of time to perform. We need to streamline the whole process and only select tests that need to be ran on a test by test basis.

**Comment by Sqeaky** [comment]
We need a simple native application that can be launched, logs what it does when its widgets are fiddled with, then writes that log to a file when closed. I made one of these recently for my full time time job. I used SWT to create native widget on the 3 platforms swiftly. SWT seems inappropriate for this project, but perhaps the core concept is useful.

**Comment by dkrutsko** [comment]
More automated tests would be nice but the nature of this library makes that difficult to do. The test cases that are there now are mostly fine but need better navigation.
