### ISSUE TITLE
Not all processes are being enumerated

### ISSUE THREAD

**Issue by dkrutsko** [Robot/robot#29]
I have observed that not all processes get enumerated on Windows in certain situations. A good example of this is a process running as another user. This needs to be further investigated. The same problem might exist with window enumeration as well.

**Comment by Sqeaky** [comment]
This will almost certainly run into security issues. It is possible that not all operating system allow enumeration of all processes from other users.

**Comment by dkrutsko** [comment]
Sorry, this was for Windows only. And you might be right.

**Comment by dkrutsko** [comment]
Okay, so it looks like this happens because the `SE_DEBUG_NAME` privilege is not enabled. Allowing users to enable this will most likely solve this issue. See #77 for a feature request enabling such functionality.

**Comment by dkrutsko** [comment]
This bug can be fixed in [Robot 2.1](https://github.com/Robot/robot/milestone/1) by calling `System::AdjustPrivilege ("SeDebugPrivilege")`. Please keep in mind that this fix is for Windows only as other platforms don't appear to have this issue.
