### ISSUE TITLE
Add the ability to check if app is running as admin

### ISSUE THREAD

**Issue by dkrutsko** [Robot/robot#38]
Today I came across this cool [library](https://github.com/coreybutler/node-windows) and one of the options there is to be able to check if the running application is running as [admin](http://stackoverflow.com/questions/29669244/how-to-know-if-node-webkit-app-is-running-with-administrator-elevated-privilege). There are quite the number of uses for this so its worth implementing.

**Comment by czipperz** [comment]
Where do you want this?

Linux and Mac: http://www.linuxquestions.org/questions/programming-9/c-codes-to-check-whether-user-is-root-or-has-admin-rights-in-linux-854996/  getuid() == 0

Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/bb776463(v=vs.85).aspx  IsUserAnAdmin()

**Comment by dkrutsko** [comment]
Hey, thanks for contributing. I'm thinking it'll be in the `Process` class, right underneath `IsSys64Bit` as a static function called `IsAdmin`

**Comment by czipperz** [comment]
I think IsSys64Bit doesn't really fit there, and IsAdmin doesn't either.  Can these be moved to a class called Environment?

**Comment by dkrutsko** [comment]
Yep, I agree, but I couldn't find a better place for it at the time. I'm thinking if we can find more of these functions of functions we can move it to a class called `System` or something.

**Comment by dkrutsko** [comment]
Okay, just to build on what @czipperz mentioned (in case we ever need it). There are three main methods of implementing this functionality on Windows. The easiest, and least robust method is simply using the [IsUserAnAdmin](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776463(v=vs.85).aspx) function. The second method is a bit more robust and is described [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376389(v=vs.85).aspx) using the `CheckTokenMembership` function. This is the method used in the original PR (#41) for this feature. The last method is the most robust, but is also quite complicated, it involves using [AccessCheck](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374815(v=vs.85).aspx) to determine user privileges. This method is described [here](https://support.microsoft.com/en-ca/help/118626/how-to-determine-whether-a-thread-is-running-in-user-context-of-local-administrator-account).
